apiVersion: v1
kind: ServiceAccount
metadata:
  name: dap-secret-webhook
  namespace: flyte
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dap-secret-webhook
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - mutatingwebhookconfigurations
    verbs:
      - get
      - create
      - update
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dap-secret-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dap-secret-webhook
subjects:
  - kind: ServiceAccount
    name: dap-secret-webhook
    namespace: flyte

