// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MLPClient is an autogenerated mock type for the MLPClient type
type MLPClient struct {
	mock.Mock
}

// GetMLPSecretValue provides a mock function with given fields: project, name
func (_m *MLPClient) GetMLPSecretValue(project string, name string) (string, error) {
	ret := _m.Called(project, name)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(project, name)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(project, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMLPClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMLPClient creates a new instance of MLPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMLPClient(t mockConstructorTestingTNewMLPClient) *MLPClient {
	mock := &MLPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
