name: DAP Secret Webhook CI Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      app_name:
        required: false
        type: string
        default: dap-secret-webhook

jobs:
  publish-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.app_name }}.${{ inputs.version }}.tar
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        id: push-image
        env:
          DOCKER_REGISTRY: ghcr.io
        run: |
           IMAGE_TAG="${{ env.DOCKER_REGISTRY }}/caraml-dev/${{ inputs.app_name }}:${{ inputs.version }}"
           docker image load --input ${{ inputs.app_name }}.${{ inputs.version }}.tar
           docker tag ${{ inputs.app_name }}:${{ inputs.version }} ${IMAGE_TAG}
           docker push ${IMAGE_TAG}